src/Entity/Setting.php
<?php

namespace App\Entity;

use App\Repository\SettingRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\DBAL\Types\Type;


#[ORM\Entity(repositoryClass: SettingRepository::class)]
class Setting
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $website_name = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?int $taxe_rate = null;

    #[ORM\Column(length: 255)]
    private ?string $logo = null;

    #[ORM\Column(length: 255)]
    private ?string $street = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    private ?string $code_postal = null;

    #[ORM\Column(length: 255)]
    private ?string $state = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(length: 255)]
    private ?string $currency = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $phone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $facebookLink = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $youtubeLink = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $instagramLink = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $copyright = null;


    
    public function __construct(Type $var = null){
        $this->setCreatedAt(new \DateTimeImmutable());

     }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getWebsiteName(): ?string
    {
        return $this->website_name;
    }

    public function setWebsiteName(string $website_name): static
    {
        $this->website_name = $website_name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getTaxeRate(): ?int
    {
        return $this->taxe_rate;
    }

    public function setTaxeRate(?int $taxe_rate): static
    {
        $this->taxe_rate = $taxe_rate;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(string $logo): static
    {
        $this->logo = $logo;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): static
    {
        $this->street = $street;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): static
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): static
    {
        $this->state = $state;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    public function setCurrency(string $currency): static
    {
        $this->currency = $currency;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getFacebookLink(): ?string
    {
        return $this->facebookLink;
    }

    public function setFacebookLink(?string $facebookLink): static
    {
        $this->facebookLink = $facebookLink;

        return $this;
    }

    public function getYoutubeLink(): ?string
    {
        return $this->youtubeLink;
    }

    public function setYoutubeLink(?string $youtubeLink): static
    {
        $this->youtubeLink = $youtubeLink;

        return $this;
    }

    public function getInstagramLink(): ?string
    {
        return $this->instagramLink;
    }

    public function setInstagramLink(?string $instagramLink): static
    {
        $this->instagramLink = $instagramLink;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getCopyright(): ?string
    {
        return $this->copyright;
    }

    public function setCopyright(?string $copyright): static
    {
        $this->copyright = $copyright;

        return $this;
    }

 
}

templates/footer/index.html.twig
<footer  class="footer_dark">
    <div  class="footer_top">
        <div  class="container">
            <div  class="row">
                <div  class="col-lg-3 col-md-6 col-sm-12">
                    <div  class="widget">
                        <div  class="footer_logo"><a  href="#">
                                <h2 >{{app.session.get("setting").WebsiteName }}</h2>
                            </a></div>
                        <p > {{app.session.get("setting").description }} </p>
                    </div>
                    <div  class="widget">
                        <ul  class="social_icons social_white">
                            <li ><a  target="_blank"
                                    href="{{app.session.get("setting").facebookLink }}"><i 
                                        class="ion-social-facebook"></i></a>
                            </li>
                            <li ></li>
                            <li ></li>
                            <li ><a  target="_blank"
                                    href="{{app.session.get("setting").youtubeLink }}"><i
                                         class="ion-social-youtube-outline"></i></a>
                            </li>
                            <li ><a  target="_blank"
                                    href="{{app.session.get("setting").instagramLink }}"><i 
                                        class="ion-social-instagram-outline"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div  class="col-lg-2 col-md-3 col-sm-6">
                    <div  class="widget">
                        <h6  class="widget_title">Useful Links</h6>
                        <ul  class="widget_links">
                          {%for foot in app.session.get("footerPages") %}
                                <li ><a 
                                 link="/page/{{foot.slug}}"
                                    href="/page/{{foot.slug}}">{{foot.title}}</a>
                                </li>

                          {%endfor%}
                            
                          
                        </ul>
                    </div>
                </div>
                <div  class="col-lg-2 col-md-3 col-sm-6">
                    <div  class="widget">
                        <h6  class="widget_title">Category</h6>
                        <ul  class="widget_links">
                            <li ><a  href="#">Men</a></li>
                            <li ><a  href="#">Woman</a></li>
                            <li ><a  href="#">Kids</a></li>
                            <li ><a  href="#">Best Saller</a>
                            </li>
                            <li ><a  href="#">New Arrivals</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div  class="col-lg-2 col-md-6 col-sm-6">
                    <div  class="widget">
                        <h6  class="widget_title">My Account</h6>
                        <ul  class="widget_links">
                            <li ><a  routerlink="account"
                                    ng-reflect-router-link="account" href="/account">My Account</a></li>
                            <li ><a  routerlink="terms"
                                    ng-reflect-router-link="terms" href="/terms">Terms</a></li>
                            <li ><a  routerlink="signin"
                                    ng-reflect-router-link="signin" href="/signin">SignIn</a></li>
                            <li ><a  routerlink="signup"
                                    ng-reflect-router-link="signup" href="/signup">Signup</a></li>
                        </ul>
                    </div>
                </div>
                <div  class="col-lg-3 col-md-4 col-sm-6">
                    <div  class="widget">
                        <h6  class="widget_title">Contact Info</h6>
                        <ul  class="contact_info contact_info_light">
                            <li ><i 
                                    class="ti-location-pin"></i>
                                <p >{{app.session.get("setting").street }} {{app.session.get("setting").codePostal }} {{app.session.get("setting").city }}</p>
                            </li>
                            <li ><i  class="ti-email"></i><a
                                     href="mailto:contact@jstore.fr">{{app.session.get("setting").email }}</a>
                            </li>
                            <li ><i  class="ti-mobile"></i>
                                <p >{{app.session.get("setting").phone }}</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div  class="bottom_footer border-top-tran">
        <div  class="container">
            <div  class="row">
                <div  class="col-md-6">
                    <p  class="mb-md-0 text-center text-md-start">{{app.session.get("setting").copyright }} </p>
                </div>
                <div  class="col-md-6">
                    <ul 
                        class="footer_payment text-center text-lg-end d-flex gap-2 justify-content-end">
                        <li ><a  href="#"><img
                                     src="assets/images/visa.png" alt="visa"></a></li>
                        <li ><a  href="#"><img
                                     src="assets/images/discover.png" alt="discover"></a>
                        </li>
                        <li ><a  href="#"><img
                                     src="assets/images/master_card.png"
                                    alt="master_card"></a></li>
                        <li ><a  href="#"><img
                                     src="assets/images/paypal.png" alt="paypal"></a></li>
                        <li ><a  href="#"><img
                                     src="assets/images/amarican_express.png"
                                    alt="amarican_express"></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>